### ISSUE TITLE
Chiarimento dashboard COVID Italia

### ISSUE THREAD

**Issue by gdesk** [heyteacher/heyteacher.github.io#1]
Buongiorno, 
navigando nella dashboard COVID Italia, in particolare nella regione "Emilia Romagna", come si nota nella seguente figura, la stringa cerchiata sembrerebbe sbagliata.
![province](https://user-images.githubusercontent.com/28731151/77224504-a0fd1c00-6b66-11ea-9f13-c9f682006a49.PNG)
Confrontando le province con quelle nei dati della figura sottostante, sono tutte presenti ed è intuibile che la dashboard relativa a "N.A." si riferisca all'ultima riga in figura.
![listaprovince](https://user-images.githubusercontent.com/28731151/77224544-21bc1800-6b67-11ea-90b3-cd1f4dc2f0d8.PNG)

Questo si ripresenta su più regioni, credo che sia un errore di svista, ma se così non fosse probabilmente non è intuibile il significato di quella dashboard nella provincia con la stringa "N.A.". Nel caso fosse una svista, probabilmente si potrebbe risolvere con l'aggiunta di una filter sui dati.

Spero di poter essere stata d'aiuto.
Buona Giornata,
Giulia

**Comment by heyteacher** [comment]
Scusa, vedo solo ora l'issue in questo repository.
N.A. sta per "Non Attribuito", una versione contratta di ciò che la Protezione Civile identifica come "In fase di definizione/aggiornamento", ossia i dati regionali che nella giornata non è riuscita ad attribuire alle province. 
Ci sono alcuni giorni che delle regioni comunicano solo di dati regionali aggregati ed è valorizzato solo "In fase di definizione/aggiornamento"

**Comment by gdesk** [comment]
Immaginavo il significato ma a livello di accessibilità forse era poco chiaro come dato. In ogni caso ha anche valori negativi in certi casi, é possibile?
Spero di non aver fatto perdere tempo era solo una puntualizzazione.
La ringrazio anche per il lavoro che state facendo.

**Comment by heyteacher** [comment]
Figurati, grazie a te, ora sostituisco "N.A." con "Non Attribuiti", effettivamente è poco chiaro.
La Protezione Civile ha fatto un ottimo lavoro pubblicando in opendata gli aggiornamenti COVID-19, ispirando dashboard come questa. 
Purtroppo i dati provenienti dalle ASL e aggregati  a livello regionale molte volte sono incompleti o errati... vanno presi con le pinze, soprattutto quelli provinciali: https://github.com/pcm-dpc/COVID-19/issues

**Comment by heyteacher** [comment]
aggiornato il sito con __NON ATTRIBUITI__ al posto di __N.A.__
Grazie e buona giornata
